# Example PV for Gitaly
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-postgresql-pv
  namespace: gitlab
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /opt/data/gitlab/postgresql  # Ensure this path exists on your node
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker02  # Replace with actual node name
