apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: postgres
  labels:
    app: postgres
spec:
  clusterIP: None  # Headless service
  selector:
    app: postgres   # Make sure this matches the labels of your StatefulSet pods
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

